#!/bin/bash

set -ueo pipefail

if [[ "${LEAF_SIGNATURE_VALID+x}" ]]
then
	if [[ "$LEAF_SIGNATURE_VALID" -eq 1 ]]
	then
		is_valid="valid "
	else
		is_valid="INVALID "
	fi
else
	is_valid=""
fi

(
	cat <<EOF
Log: ${LOG_ENDPOINT}
Leaf index: ${LEAF_INDEX}
Keyhash: ${KEY_HASH}
Checksum: ${LEAF_CHECKSUM}
EOF

	for hook in "${!LEAF_INFO_@}"
	do
		echo
		echo "Auxiliary leaf info (${hook:10}):"
		echo "------------------------------------------------------------------------"
		echo "${!hook}"
		echo "------------------------------------------------------------------------"
	done
) | mail -s "New ${is_valid}signature from \"${KEY_NAME}\" on ${LOG_ENDPOINT} (index ${LEAF_INDEX})" "$HOOK_PARAM_address"
